#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 17 10:44:01 2021

@author: valentinmerault
"""

from tkinter import *

# Fonction :
def carre(x, y, coul,ecart):
    "Permet de tracer des carre, utile au damier."
    cnv.create_rectangle(x, y, x + ecart, y + ecart, fill=coul)


def cercle(x, y, r, coul):
    "Permet de tracer les pions des joueurs"
    cnv.create_oval(x - r, y - r, x + r, y + r, fill=coul)


def plateau(start,y,ecart):
    "Permet de créer le plateau de jeux"

    for i in range(10):
        x = start
        for j in range(10):

            if (i + j) % 2 == 0:
                carre(x, y, "ivory",ecart)
            else:
                carre(x, y, "brown",ecart)
            x += ecart
        y += ecart


def initPionsNoirs(SIZE,pad,pady,x,y,ecart):
    "Permet de placer les pions du joueur noir"

    for i in range(4):
        print("x : ",x)
        for j in range(5):
            cnv.create_oval(x + pad , y +pad , x + ecart-pad, y + ecart-pad, fill="black")
            x += pady*2
            print(x)

        y += pady
        if i%2 == 0:
            x = SIZE * 0.02
        else:
            x = ecart

def initPionsBlanc(SIZE,pad,pady,x,y,ecart):
    "Permet de placer les pions du joueur blanc"

    for i in range(4):

        for j in range(5):
            cnv.create_oval(x + pad, y + pad, x + ecart, y + ecart, fill="#E2BC74")
            x += pady*2

        y -= pady
        if i%2 == 0:
            x -= SIZE - 65
        else:
            x -= SIZE + 35


# On crée les variables utiles aux différents fonctions.
SIZE = 500  # Longueur et Hauteur du canvas.
pad = SIZE * 0.008
pady = SIZE * 0.1
ecart = SIZE * 0.1
x = SIZE * 0.02
y = SIZE * 0.02

# Affichage :
fen = Tk()
fen.resizable(width=0, height=0) # Rend impossible le redimensionnement de la fenêtre.

cnv = Canvas(fen, width=SIZE+SIZE*0.03, height=SIZE+SIZE*0.03, bg="ivory")
cnv.pack()

# Interface Graphique :

# On appel les fonctions :
plateau(x,y,ecart)
initPionsNoirs(SIZE,pad,pady,x,y,ecart)
#initPionsBlanc(SIZE,pad,pady,x,y, ecart)

fen.mainloop()
